dataset:
  train_img_root : /data/segformer/scformer/data/polyp/TrainDataset/images/
  train_label_root: /data/segformer/scformer/data/polyp/TrainDataset/masks_new/

  test_CVC-300_img : /data/segformer/scformer/data/polyp/TestDataset/CVC-300/images/
  test_CVC-300_label : /data/segformer/scformer/data/polyp/TestDataset/CVC-300/masks_new/

  test_CVC-ClinicDB_img : /data/segformer/scformer/data/polyp/TestDataset/CVC-ClinicDB/images/
  test_CVC-ClinicDB_label : /data/segformer/scformer/data/polyp/TestDataset/CVC-ClinicDB/masks_new/

  test_CVC-ColonDB_img : /data/segformer/scformer/data/polyp/TestDataset/CVC-ColonDB/images/
  test_CVC-ColonDB_label : /data/segformer/scformer/data/polyp/TestDataset/CVC-ColonDB/masks_new/

  test_ETIS-LaribPolypDB_img : /data/segformer/scformer/data/polyp/TestDataset/ETIS-LaribPolypDB/images/
  test_ETIS-LaribPolypDB_label : /data/segformer/scformer/data/polyp/TestDataset/ETIS-LaribPolypDB/masks_new/

  test_Kvasir_img : /data/segformer/scformer/data/polyp/TestDataset/Kvasir/images/
  test_Kvasir_label : /data/segformer/scformer/data/polyp/TestDataset/Kvasir/masks_new/

  class_num: 2

  crop_size : 
    w: 352
    h: 352
  batch_size : 8
  num_workers : 8

# sct_b1
# sct_dw_b1
# sct_pixel_b1
# sct_dw_pixel_b1

model:
  model_name : segformer_b2

training:
  device : cuda
  lr : 1e-4
  max_epoch : 230

other:
  checkpoint_save_path : /data/segformer/scformer/train_package/polyp_collection/segformer_b2_pretrained
  logger_path : /data/segformer/scformer/train_package/polyp_collection/segformer_b2_pretrained/segformer_b2_pretrained.log

test:
  checkpoint_save_path : /data/segformer/scformer/train_package/polyp_collection/segformer_b2_pretrained/val_best.pth
