dataset:
  train_img_root : /data/segformer/scformer/data/polyp/TrainDataset/images/
  train_label_root: /data/segformer/scformer/data/polyp/TrainDataset/masks_new/

  test_CVC-300_img : /data/segformer/scformer/data/polyp/TestDataset/CVC-300/images/
  test_CVC-300_label : /data/segformer/scformer/data/polyp/TestDataset/CVC-300/masks_new/

  test_CVC-ClinicDB_img : /data/segformer/scformer/data/polyp/TestDataset/CVC-ClinicDB/images/
  test_CVC-ClinicDB_label : /data/segformer/scformer/data/polyp/TestDataset/CVC-ClinicDB/masks_new/

  test_CVC-ColonDB_img : /data/segformer/scformer/data/polyp/TestDataset/CVC-ColonDB/images/
  test_CVC-ColonDB_label : /data/segformer/scformer/data/polyp/TestDataset/CVC-ColonDB/masks_new/

  test_ETIS-LaribPolypDB_img : /data/segformer/scformer/data/polyp/TestDataset/ETIS-LaribPolypDB/images/
  test_ETIS-LaribPolypDB_label : /data/segformer/scformer/data/polyp/TestDataset/ETIS-LaribPolypDB/masks_new/

  test_Kvasir_img : /data/segformer/scformer/data/polyp/TestDataset/Kvasir/images/
  test_Kvasir_label : /data/segformer/scformer/data/polyp/TestDataset/Kvasir/masks_new/

  class_num: 2

  crop_size : 
    w: 352
    h: 352
  batch_size : 16
  num_workers : 8


Train_transform_list:
  resize: 
      size: [352, 352]
  random_scale_crop:
      range: [0.75, 1.25]
  random_flip:
      lr: True
      ud: True
  random_rotate:
      range: [0, 359]
  random_image_enhance:
      methods: ['contrast', 'sharpness', 'brightness']
  random_dilation_erosion:
      kernel_range: [2, 5]
  tonumpy: NULL
  normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  totensor: NULL

Val_transform_list:
  resize: 
      size: [352, 352]
  tonumpy: NULL
  normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  totensor: NULL


model:
  model_name : scale_model
  is_pretrained : True
  pretrained_path : /data/segformer/scformer/train_package/imageNet_pretrain/train_best.pth

training:
  device : cuda
  lr : 1e-4
  max_epoch : 200
  evl_epoch : 0

other:
  checkpoint_save_path : /data/segformer/scformer/train_package/polyp_collection/scale_model/
  logger_path : /data/segformer/scformer/train_package/polyp_collection/scale_model/feilong_test.log

test:
  checkpoint_save_path : /data/segformer/scformer/train_package/polyp_collection/scale_model/val_best.pth
