dataset:
  train_img_root : /data/segformer/scformer/data/CVC-ClinicDB/train/
  val_img_root : /data/segformer/scformer/data/CVC-ClinicDB/val/
  test_img_root : /data/segformer/scformer/data/CVC-ClinicDB/test/

  train_label_root: /data/segformer/scformer/data/CVC-ClinicDB/train_labels/
  val_label_root : /data/segformer/scformer/data/CVC-ClinicDB/val_labels/
  test_label_root : /data/segformer/scformer/data/CVC-ClinicDB/test_labels/

  class_num: 2

  crop_size : 
    w: 512
    h: 512
  batch_size : 8
  num_workers : 8

model:
  model_name : sct_b1

training:
  device : cuda
  lr : 1e-4
  max_epoch : 10000

other:
  checkpoint_save_path : /data/segformer/scformer/train_package/sct_b1_cvc
  logger_path : /data/segformer/scformer/train_package/sct_b1_cvc/sct_b1_cvc.log

test:
  checkpoint_save_path : /data/segformer/scformer/train_package/sct_b1_cvc/val_best.pth
